FROM fedora:latest

LABEL maintainer="Alexander Zaitsev <zamazan4ik@tut.by>"

ARG STICKER2SMILEBOT_SOURCE_URL=https://github.com/ZaMaZaN4iK/sticker2smilebot-telegram.git

RUN dnf install -y ca-certificates perl autoconf automake libtool clang cmake make git python3-pip \
    && pip install conan

WORKDIR /usr/src/sticker2smilebot-telegram

RUN git clone ${STICKER2SMILEBOT_SOURCE_URL}

WORKDIR sticker2smilebot-telegram

RUN CC=clang CXX=clang++ cmake -B build -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build --target install && \
    rm -rf /usr/src/sticker2smilebot-telegram

WORKDIR /usr/local/bin

ENTRYPOINT ["/usr/local/bin/sticker2smilebot_telegram"]

