FROM fedora:latest

LABEL maintainer="Alexander Zaitsev <zamazan4ik@tut.by>"

RUN dnf install -y ca-certificates perl autoconf automake libtool clang cmake make python3-pip \
    && pip install conan

WORKDIR /usr/src/sticker2smilebot-telegram
COPY main.cpp ./
COPY CMakeLists.txt ./

RUN CC=clang CXX=clang++ cmake -B build -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build --target install && \
    rm -rf /usr/src/sticker2smilebot-telegram

WORKDIR /usr/local/bin

ENTRYPOINT ["/usr/local/bin/sticker2smilebot_telegram"]

