FROM fedora:latest

LABEL maintainer="Alexander Zaitsev <zamazan4ik@tut.by>"

ARG STICKER2SMILEBOT_VERSION=1.0.2

ARG STICKER2SMILEBOT_SOURCE_URL=https://github.com/ZaMaZaN4iK/sticker2smilebot-telegram/archive/v${STICKER2SMILEBOT_VERSION}.zip

RUN dnf install -y ca-certificates perl autoconf automake libtool wget unzip clang cmake make python3-pip \
    && pip install conan

WORKDIR /usr/src/sticker2smilebot-telegram

RUN wget ${STICKER2SMILEBOT_SOURCE_URL} && unzip v${STICKER2SMILEBOT_VERSION}.zip

WORKDIR sticker2smilebot-telegram-${STICKER2SMILEBOT_VERSION}

RUN CC=clang CXX=clang++ cmake -B build -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build --target install && \
    rm -rf /usr/src/sticker2smilebot-telegram

WORKDIR /usr/local/bin

ENTRYPOINT ["/usr/local/bin/sticker2smilebot_telegram"]

